name: Build and Deploy
on:
  push:
    branches:
      - io
permissions:
  contents: write
jobs:
  build-and-deploy:
    # concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        main: 'dist/'

      - name: Install ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm install

      - name: build
        run: npm run build
      - name: replace
        with:
          directory: /dist

        #  folder: dist # The folder the action should deploy.

        # with:
        #   name: build-pages
        #   path: build
      # - name: deploy
      #   uses: JamesIves/github-pages-deploy-action@v4.2.3
      #   with:
      #     branch: io
      #     folder: dist
      #     token: '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'
