name: bbb324.github.io deploy
run-name: bbb324 is testing out GitHub Actions ğŸš€
on:
  push:
    branckes:
      - io
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          node: 16.14
      - run: npm install && npm run build
  Deploy:
    needs: Build # ç¡®ä¿build é˜¶æ®µå®Œæˆ
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm run build

        # with:
        #   name: build-pages
        #   path: build
      # - name: deploy
      #   uses: JamesIves/github-pages-deploy-action@v4.2.3
      #   with:
      #     branch: io
      #     folder: dist
      #     token: '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'
