name: bbb324.github.io deploy
run-name: bbb324 is testing out GitHub Actions ğŸš€
on:
  push:
    branckes:
      - io
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: actions/setup-node@v3
        uses: actions/setup-node@v3
        with:
          node: 16.14
      # - name: yarn cache
      #   id: yarn-cahce-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)"
      # - uses: actions/cache@v2
      #   id: yarn-cache
      #   with:
      #     path: ${{ steps.yarn-cahce-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      - run: npm install && npm run build
  Deploy:
    needs: Build # ç¡®ä¿build é˜¶æ®µå®Œæˆ
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: download build files
        uses: actions/download-artifact@v3
        with:
          name: build-pages
          path: build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: io
          folder: dist
          token: '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'
